package com.springboot.redis.cache.model;

import java.io.Serializable;
import java.util.Date;

public class User  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_area_code
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String mobileAreaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.avatar
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String genderValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.height
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.weight
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birth_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identity_type_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String identityTypeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.identity_no
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String identityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nationality_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String nationalityValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.native_place
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String nativePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.registered_permanent_residence
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String registeredPermanentResidence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ethnic_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String ethnicValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.political_status_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String politicalStatusValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.health_condition_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String healthConditionValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.health_descr
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String healthDescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.marital_status_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String maritalStatusValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.marriage_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private Date marriageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.criminal_record_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String criminalRecordValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.criminal_descr
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private String criminalDescr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.first_work_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private Date firstWorkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.deleted
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_time
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_time
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_area_code
     *
     * @return the value of user.mobile_area_code
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getMobileAreaCode() {
        return mobileAreaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_area_code
     *
     * @param mobileAreaCode the value for user.mobile_area_code
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setMobileAreaCode(String mobileAreaCode) {
        this.mobileAreaCode = mobileAreaCode == null ? null : mobileAreaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.avatar
     *
     * @return the value of user.avatar
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.avatar
     *
     * @param avatar the value for user.avatar
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender_value
     *
     * @return the value of user.gender_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getGenderValue() {
        return genderValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender_value
     *
     * @param genderValue the value for user.gender_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setGenderValue(String genderValue) {
        this.genderValue = genderValue == null ? null : genderValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.height
     *
     * @return the value of user.height
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.height
     *
     * @param height the value for user.height
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.weight
     *
     * @return the value of user.weight
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.weight
     *
     * @param weight the value for user.weight
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birth_date
     *
     * @return the value of user.birth_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birth_date
     *
     * @param birthDate the value for user.birth_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identity_type_value
     *
     * @return the value of user.identity_type_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getIdentityTypeValue() {
        return identityTypeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identity_type_value
     *
     * @param identityTypeValue the value for user.identity_type_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setIdentityTypeValue(String identityTypeValue) {
        this.identityTypeValue = identityTypeValue == null ? null : identityTypeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.identity_no
     *
     * @return the value of user.identity_no
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.identity_no
     *
     * @param identityNo the value for user.identity_no
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo == null ? null : identityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nationality_value
     *
     * @return the value of user.nationality_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getNationalityValue() {
        return nationalityValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nationality_value
     *
     * @param nationalityValue the value for user.nationality_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setNationalityValue(String nationalityValue) {
        this.nationalityValue = nationalityValue == null ? null : nationalityValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.native_place
     *
     * @return the value of user.native_place
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.native_place
     *
     * @param nativePlace the value for user.native_place
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.registered_permanent_residence
     *
     * @return the value of user.registered_permanent_residence
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getRegisteredPermanentResidence() {
        return registeredPermanentResidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.registered_permanent_residence
     *
     * @param registeredPermanentResidence the value for user.registered_permanent_residence
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setRegisteredPermanentResidence(String registeredPermanentResidence) {
        this.registeredPermanentResidence = registeredPermanentResidence == null ? null : registeredPermanentResidence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ethnic_value
     *
     * @return the value of user.ethnic_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getEthnicValue() {
        return ethnicValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ethnic_value
     *
     * @param ethnicValue the value for user.ethnic_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setEthnicValue(String ethnicValue) {
        this.ethnicValue = ethnicValue == null ? null : ethnicValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.political_status_value
     *
     * @return the value of user.political_status_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getPoliticalStatusValue() {
        return politicalStatusValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.political_status_value
     *
     * @param politicalStatusValue the value for user.political_status_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setPoliticalStatusValue(String politicalStatusValue) {
        this.politicalStatusValue = politicalStatusValue == null ? null : politicalStatusValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.health_condition_value
     *
     * @return the value of user.health_condition_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getHealthConditionValue() {
        return healthConditionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.health_condition_value
     *
     * @param healthConditionValue the value for user.health_condition_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setHealthConditionValue(String healthConditionValue) {
        this.healthConditionValue = healthConditionValue == null ? null : healthConditionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.health_descr
     *
     * @return the value of user.health_descr
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getHealthDescr() {
        return healthDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.health_descr
     *
     * @param healthDescr the value for user.health_descr
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setHealthDescr(String healthDescr) {
        this.healthDescr = healthDescr == null ? null : healthDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.marital_status_value
     *
     * @return the value of user.marital_status_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getMaritalStatusValue() {
        return maritalStatusValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.marital_status_value
     *
     * @param maritalStatusValue the value for user.marital_status_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setMaritalStatusValue(String maritalStatusValue) {
        this.maritalStatusValue = maritalStatusValue == null ? null : maritalStatusValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.marriage_date
     *
     * @return the value of user.marriage_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Date getMarriageDate() {
        return marriageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.marriage_date
     *
     * @param marriageDate the value for user.marriage_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setMarriageDate(Date marriageDate) {
        this.marriageDate = marriageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.criminal_record_value
     *
     * @return the value of user.criminal_record_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getCriminalRecordValue() {
        return criminalRecordValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.criminal_record_value
     *
     * @param criminalRecordValue the value for user.criminal_record_value
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setCriminalRecordValue(String criminalRecordValue) {
        this.criminalRecordValue = criminalRecordValue == null ? null : criminalRecordValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.criminal_descr
     *
     * @return the value of user.criminal_descr
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getCriminalDescr() {
        return criminalDescr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.criminal_descr
     *
     * @param criminalDescr the value for user.criminal_descr
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setCriminalDescr(String criminalDescr) {
        this.criminalDescr = criminalDescr == null ? null : criminalDescr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.first_work_date
     *
     * @return the value of user.first_work_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Date getFirstWorkDate() {
        return firstWorkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.first_work_date
     *
     * @param firstWorkDate the value for user.first_work_date
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setFirstWorkDate(Date firstWorkDate) {
        this.firstWorkDate = firstWorkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.deleted
     *
     * @return the value of user.deleted
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.deleted
     *
     * @param deleted the value for user.deleted
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_time
     *
     * @return the value of user.created_time
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_time
     *
     * @param createdTime the value for user.created_time
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updated_time
     *
     * @return the value of user.updated_time
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updated_time
     *
     * @param updatedTime the value for user.updated_time
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}