package com.springboot.redis.cache.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeIsNull() {
            addCriterion("mobile_area_code is null");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeIsNotNull() {
            addCriterion("mobile_area_code is not null");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeEqualTo(String value) {
            addCriterion("mobile_area_code =", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeNotEqualTo(String value) {
            addCriterion("mobile_area_code <>", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeGreaterThan(String value) {
            addCriterion("mobile_area_code >", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mobile_area_code >=", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeLessThan(String value) {
            addCriterion("mobile_area_code <", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeLessThanOrEqualTo(String value) {
            addCriterion("mobile_area_code <=", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeLike(String value) {
            addCriterion("mobile_area_code like", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeNotLike(String value) {
            addCriterion("mobile_area_code not like", value, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeIn(List<String> values) {
            addCriterion("mobile_area_code in", values, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeNotIn(List<String> values) {
            addCriterion("mobile_area_code not in", values, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeBetween(String value1, String value2) {
            addCriterion("mobile_area_code between", value1, value2, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andMobileAreaCodeNotBetween(String value1, String value2) {
            addCriterion("mobile_area_code not between", value1, value2, "mobileAreaCode");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("avatar is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("avatar =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("avatar <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("avatar >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("avatar >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("avatar <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("avatar <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("avatar like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("avatar not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("avatar in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("avatar not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("avatar between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("avatar not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andGenderValueIsNull() {
            addCriterion("gender_value is null");
            return (Criteria) this;
        }

        public Criteria andGenderValueIsNotNull() {
            addCriterion("gender_value is not null");
            return (Criteria) this;
        }

        public Criteria andGenderValueEqualTo(String value) {
            addCriterion("gender_value =", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueNotEqualTo(String value) {
            addCriterion("gender_value <>", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueGreaterThan(String value) {
            addCriterion("gender_value >", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueGreaterThanOrEqualTo(String value) {
            addCriterion("gender_value >=", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueLessThan(String value) {
            addCriterion("gender_value <", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueLessThanOrEqualTo(String value) {
            addCriterion("gender_value <=", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueLike(String value) {
            addCriterion("gender_value like", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueNotLike(String value) {
            addCriterion("gender_value not like", value, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueIn(List<String> values) {
            addCriterion("gender_value in", values, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueNotIn(List<String> values) {
            addCriterion("gender_value not in", values, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueBetween(String value1, String value2) {
            addCriterion("gender_value between", value1, value2, "genderValue");
            return (Criteria) this;
        }

        public Criteria andGenderValueNotBetween(String value1, String value2) {
            addCriterion("gender_value not between", value1, value2, "genderValue");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("height like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("height not like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<String> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<String> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(String value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(String value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(String value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(String value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(String value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(String value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLike(String value) {
            addCriterion("weight like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotLike(String value) {
            addCriterion("weight not like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<String> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<String> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(String value1, String value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(String value1, String value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andBirthDateIsNull() {
            addCriterion("birth_date is null");
            return (Criteria) this;
        }

        public Criteria andBirthDateIsNotNull() {
            addCriterion("birth_date is not null");
            return (Criteria) this;
        }

        public Criteria andBirthDateEqualTo(Date value) {
            addCriterionForJDBCDate("birth_date =", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("birth_date <>", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateGreaterThan(Date value) {
            addCriterionForJDBCDate("birth_date >", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birth_date >=", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLessThan(Date value) {
            addCriterionForJDBCDate("birth_date <", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birth_date <=", value, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateIn(List<Date> values) {
            addCriterionForJDBCDate("birth_date in", values, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("birth_date not in", values, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birth_date between", value1, value2, "birthDate");
            return (Criteria) this;
        }

        public Criteria andBirthDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birth_date not between", value1, value2, "birthDate");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueIsNull() {
            addCriterion("identity_type_value is null");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueIsNotNull() {
            addCriterion("identity_type_value is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueEqualTo(String value) {
            addCriterion("identity_type_value =", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueNotEqualTo(String value) {
            addCriterion("identity_type_value <>", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueGreaterThan(String value) {
            addCriterion("identity_type_value >", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueGreaterThanOrEqualTo(String value) {
            addCriterion("identity_type_value >=", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueLessThan(String value) {
            addCriterion("identity_type_value <", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueLessThanOrEqualTo(String value) {
            addCriterion("identity_type_value <=", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueLike(String value) {
            addCriterion("identity_type_value like", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueNotLike(String value) {
            addCriterion("identity_type_value not like", value, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueIn(List<String> values) {
            addCriterion("identity_type_value in", values, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueNotIn(List<String> values) {
            addCriterion("identity_type_value not in", values, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueBetween(String value1, String value2) {
            addCriterion("identity_type_value between", value1, value2, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityTypeValueNotBetween(String value1, String value2) {
            addCriterion("identity_type_value not between", value1, value2, "identityTypeValue");
            return (Criteria) this;
        }

        public Criteria andIdentityNoIsNull() {
            addCriterion("identity_no is null");
            return (Criteria) this;
        }

        public Criteria andIdentityNoIsNotNull() {
            addCriterion("identity_no is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityNoEqualTo(String value) {
            addCriterion("identity_no =", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotEqualTo(String value) {
            addCriterion("identity_no <>", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoGreaterThan(String value) {
            addCriterion("identity_no >", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoGreaterThanOrEqualTo(String value) {
            addCriterion("identity_no >=", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoLessThan(String value) {
            addCriterion("identity_no <", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoLessThanOrEqualTo(String value) {
            addCriterion("identity_no <=", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoLike(String value) {
            addCriterion("identity_no like", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotLike(String value) {
            addCriterion("identity_no not like", value, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoIn(List<String> values) {
            addCriterion("identity_no in", values, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotIn(List<String> values) {
            addCriterion("identity_no not in", values, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoBetween(String value1, String value2) {
            addCriterion("identity_no between", value1, value2, "identityNo");
            return (Criteria) this;
        }

        public Criteria andIdentityNoNotBetween(String value1, String value2) {
            addCriterion("identity_no not between", value1, value2, "identityNo");
            return (Criteria) this;
        }

        public Criteria andNationalityValueIsNull() {
            addCriterion("nationality_value is null");
            return (Criteria) this;
        }

        public Criteria andNationalityValueIsNotNull() {
            addCriterion("nationality_value is not null");
            return (Criteria) this;
        }

        public Criteria andNationalityValueEqualTo(String value) {
            addCriterion("nationality_value =", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueNotEqualTo(String value) {
            addCriterion("nationality_value <>", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueGreaterThan(String value) {
            addCriterion("nationality_value >", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueGreaterThanOrEqualTo(String value) {
            addCriterion("nationality_value >=", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueLessThan(String value) {
            addCriterion("nationality_value <", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueLessThanOrEqualTo(String value) {
            addCriterion("nationality_value <=", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueLike(String value) {
            addCriterion("nationality_value like", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueNotLike(String value) {
            addCriterion("nationality_value not like", value, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueIn(List<String> values) {
            addCriterion("nationality_value in", values, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueNotIn(List<String> values) {
            addCriterion("nationality_value not in", values, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueBetween(String value1, String value2) {
            addCriterion("nationality_value between", value1, value2, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNationalityValueNotBetween(String value1, String value2) {
            addCriterion("nationality_value not between", value1, value2, "nationalityValue");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNull() {
            addCriterion("native_place is null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIsNotNull() {
            addCriterion("native_place is not null");
            return (Criteria) this;
        }

        public Criteria andNativePlaceEqualTo(String value) {
            addCriterion("native_place =", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotEqualTo(String value) {
            addCriterion("native_place <>", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThan(String value) {
            addCriterion("native_place >", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceGreaterThanOrEqualTo(String value) {
            addCriterion("native_place >=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThan(String value) {
            addCriterion("native_place <", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLessThanOrEqualTo(String value) {
            addCriterion("native_place <=", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceLike(String value) {
            addCriterion("native_place like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotLike(String value) {
            addCriterion("native_place not like", value, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceIn(List<String> values) {
            addCriterion("native_place in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotIn(List<String> values) {
            addCriterion("native_place not in", values, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceBetween(String value1, String value2) {
            addCriterion("native_place between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andNativePlaceNotBetween(String value1, String value2) {
            addCriterion("native_place not between", value1, value2, "nativePlace");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceIsNull() {
            addCriterion("registered_permanent_residence is null");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceIsNotNull() {
            addCriterion("registered_permanent_residence is not null");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceEqualTo(String value) {
            addCriterion("registered_permanent_residence =", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceNotEqualTo(String value) {
            addCriterion("registered_permanent_residence <>", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceGreaterThan(String value) {
            addCriterion("registered_permanent_residence >", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceGreaterThanOrEqualTo(String value) {
            addCriterion("registered_permanent_residence >=", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceLessThan(String value) {
            addCriterion("registered_permanent_residence <", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceLessThanOrEqualTo(String value) {
            addCriterion("registered_permanent_residence <=", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceLike(String value) {
            addCriterion("registered_permanent_residence like", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceNotLike(String value) {
            addCriterion("registered_permanent_residence not like", value, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceIn(List<String> values) {
            addCriterion("registered_permanent_residence in", values, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceNotIn(List<String> values) {
            addCriterion("registered_permanent_residence not in", values, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceBetween(String value1, String value2) {
            addCriterion("registered_permanent_residence between", value1, value2, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andRegisteredPermanentResidenceNotBetween(String value1, String value2) {
            addCriterion("registered_permanent_residence not between", value1, value2, "registeredPermanentResidence");
            return (Criteria) this;
        }

        public Criteria andEthnicValueIsNull() {
            addCriterion("ethnic_value is null");
            return (Criteria) this;
        }

        public Criteria andEthnicValueIsNotNull() {
            addCriterion("ethnic_value is not null");
            return (Criteria) this;
        }

        public Criteria andEthnicValueEqualTo(String value) {
            addCriterion("ethnic_value =", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueNotEqualTo(String value) {
            addCriterion("ethnic_value <>", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueGreaterThan(String value) {
            addCriterion("ethnic_value >", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueGreaterThanOrEqualTo(String value) {
            addCriterion("ethnic_value >=", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueLessThan(String value) {
            addCriterion("ethnic_value <", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueLessThanOrEqualTo(String value) {
            addCriterion("ethnic_value <=", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueLike(String value) {
            addCriterion("ethnic_value like", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueNotLike(String value) {
            addCriterion("ethnic_value not like", value, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueIn(List<String> values) {
            addCriterion("ethnic_value in", values, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueNotIn(List<String> values) {
            addCriterion("ethnic_value not in", values, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueBetween(String value1, String value2) {
            addCriterion("ethnic_value between", value1, value2, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andEthnicValueNotBetween(String value1, String value2) {
            addCriterion("ethnic_value not between", value1, value2, "ethnicValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueIsNull() {
            addCriterion("political_status_value is null");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueIsNotNull() {
            addCriterion("political_status_value is not null");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueEqualTo(String value) {
            addCriterion("political_status_value =", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueNotEqualTo(String value) {
            addCriterion("political_status_value <>", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueGreaterThan(String value) {
            addCriterion("political_status_value >", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueGreaterThanOrEqualTo(String value) {
            addCriterion("political_status_value >=", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueLessThan(String value) {
            addCriterion("political_status_value <", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueLessThanOrEqualTo(String value) {
            addCriterion("political_status_value <=", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueLike(String value) {
            addCriterion("political_status_value like", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueNotLike(String value) {
            addCriterion("political_status_value not like", value, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueIn(List<String> values) {
            addCriterion("political_status_value in", values, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueNotIn(List<String> values) {
            addCriterion("political_status_value not in", values, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueBetween(String value1, String value2) {
            addCriterion("political_status_value between", value1, value2, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andPoliticalStatusValueNotBetween(String value1, String value2) {
            addCriterion("political_status_value not between", value1, value2, "politicalStatusValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueIsNull() {
            addCriterion("health_condition_value is null");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueIsNotNull() {
            addCriterion("health_condition_value is not null");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueEqualTo(String value) {
            addCriterion("health_condition_value =", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueNotEqualTo(String value) {
            addCriterion("health_condition_value <>", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueGreaterThan(String value) {
            addCriterion("health_condition_value >", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueGreaterThanOrEqualTo(String value) {
            addCriterion("health_condition_value >=", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueLessThan(String value) {
            addCriterion("health_condition_value <", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueLessThanOrEqualTo(String value) {
            addCriterion("health_condition_value <=", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueLike(String value) {
            addCriterion("health_condition_value like", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueNotLike(String value) {
            addCriterion("health_condition_value not like", value, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueIn(List<String> values) {
            addCriterion("health_condition_value in", values, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueNotIn(List<String> values) {
            addCriterion("health_condition_value not in", values, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueBetween(String value1, String value2) {
            addCriterion("health_condition_value between", value1, value2, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthConditionValueNotBetween(String value1, String value2) {
            addCriterion("health_condition_value not between", value1, value2, "healthConditionValue");
            return (Criteria) this;
        }

        public Criteria andHealthDescrIsNull() {
            addCriterion("health_descr is null");
            return (Criteria) this;
        }

        public Criteria andHealthDescrIsNotNull() {
            addCriterion("health_descr is not null");
            return (Criteria) this;
        }

        public Criteria andHealthDescrEqualTo(String value) {
            addCriterion("health_descr =", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrNotEqualTo(String value) {
            addCriterion("health_descr <>", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrGreaterThan(String value) {
            addCriterion("health_descr >", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrGreaterThanOrEqualTo(String value) {
            addCriterion("health_descr >=", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrLessThan(String value) {
            addCriterion("health_descr <", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrLessThanOrEqualTo(String value) {
            addCriterion("health_descr <=", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrLike(String value) {
            addCriterion("health_descr like", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrNotLike(String value) {
            addCriterion("health_descr not like", value, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrIn(List<String> values) {
            addCriterion("health_descr in", values, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrNotIn(List<String> values) {
            addCriterion("health_descr not in", values, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrBetween(String value1, String value2) {
            addCriterion("health_descr between", value1, value2, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andHealthDescrNotBetween(String value1, String value2) {
            addCriterion("health_descr not between", value1, value2, "healthDescr");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueIsNull() {
            addCriterion("marital_status_value is null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueIsNotNull() {
            addCriterion("marital_status_value is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueEqualTo(String value) {
            addCriterion("marital_status_value =", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueNotEqualTo(String value) {
            addCriterion("marital_status_value <>", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueGreaterThan(String value) {
            addCriterion("marital_status_value >", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueGreaterThanOrEqualTo(String value) {
            addCriterion("marital_status_value >=", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueLessThan(String value) {
            addCriterion("marital_status_value <", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueLessThanOrEqualTo(String value) {
            addCriterion("marital_status_value <=", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueLike(String value) {
            addCriterion("marital_status_value like", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueNotLike(String value) {
            addCriterion("marital_status_value not like", value, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueIn(List<String> values) {
            addCriterion("marital_status_value in", values, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueNotIn(List<String> values) {
            addCriterion("marital_status_value not in", values, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueBetween(String value1, String value2) {
            addCriterion("marital_status_value between", value1, value2, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusValueNotBetween(String value1, String value2) {
            addCriterion("marital_status_value not between", value1, value2, "maritalStatusValue");
            return (Criteria) this;
        }

        public Criteria andMarriageDateIsNull() {
            addCriterion("marriage_date is null");
            return (Criteria) this;
        }

        public Criteria andMarriageDateIsNotNull() {
            addCriterion("marriage_date is not null");
            return (Criteria) this;
        }

        public Criteria andMarriageDateEqualTo(Date value) {
            addCriterionForJDBCDate("marriage_date =", value, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("marriage_date <>", value, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateGreaterThan(Date value) {
            addCriterionForJDBCDate("marriage_date >", value, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("marriage_date >=", value, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateLessThan(Date value) {
            addCriterionForJDBCDate("marriage_date <", value, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("marriage_date <=", value, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateIn(List<Date> values) {
            addCriterionForJDBCDate("marriage_date in", values, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("marriage_date not in", values, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("marriage_date between", value1, value2, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andMarriageDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("marriage_date not between", value1, value2, "marriageDate");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueIsNull() {
            addCriterion("criminal_record_value is null");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueIsNotNull() {
            addCriterion("criminal_record_value is not null");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueEqualTo(String value) {
            addCriterion("criminal_record_value =", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueNotEqualTo(String value) {
            addCriterion("criminal_record_value <>", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueGreaterThan(String value) {
            addCriterion("criminal_record_value >", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueGreaterThanOrEqualTo(String value) {
            addCriterion("criminal_record_value >=", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueLessThan(String value) {
            addCriterion("criminal_record_value <", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueLessThanOrEqualTo(String value) {
            addCriterion("criminal_record_value <=", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueLike(String value) {
            addCriterion("criminal_record_value like", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueNotLike(String value) {
            addCriterion("criminal_record_value not like", value, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueIn(List<String> values) {
            addCriterion("criminal_record_value in", values, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueNotIn(List<String> values) {
            addCriterion("criminal_record_value not in", values, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueBetween(String value1, String value2) {
            addCriterion("criminal_record_value between", value1, value2, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalRecordValueNotBetween(String value1, String value2) {
            addCriterion("criminal_record_value not between", value1, value2, "criminalRecordValue");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrIsNull() {
            addCriterion("criminal_descr is null");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrIsNotNull() {
            addCriterion("criminal_descr is not null");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrEqualTo(String value) {
            addCriterion("criminal_descr =", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrNotEqualTo(String value) {
            addCriterion("criminal_descr <>", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrGreaterThan(String value) {
            addCriterion("criminal_descr >", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrGreaterThanOrEqualTo(String value) {
            addCriterion("criminal_descr >=", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrLessThan(String value) {
            addCriterion("criminal_descr <", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrLessThanOrEqualTo(String value) {
            addCriterion("criminal_descr <=", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrLike(String value) {
            addCriterion("criminal_descr like", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrNotLike(String value) {
            addCriterion("criminal_descr not like", value, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrIn(List<String> values) {
            addCriterion("criminal_descr in", values, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrNotIn(List<String> values) {
            addCriterion("criminal_descr not in", values, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrBetween(String value1, String value2) {
            addCriterion("criminal_descr between", value1, value2, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andCriminalDescrNotBetween(String value1, String value2) {
            addCriterion("criminal_descr not between", value1, value2, "criminalDescr");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateIsNull() {
            addCriterion("first_work_date is null");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateIsNotNull() {
            addCriterion("first_work_date is not null");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateEqualTo(Date value) {
            addCriterionForJDBCDate("first_work_date =", value, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("first_work_date <>", value, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateGreaterThan(Date value) {
            addCriterionForJDBCDate("first_work_date >", value, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("first_work_date >=", value, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateLessThan(Date value) {
            addCriterionForJDBCDate("first_work_date <", value, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("first_work_date <=", value, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateIn(List<Date> values) {
            addCriterionForJDBCDate("first_work_date in", values, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("first_work_date not in", values, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("first_work_date between", value1, value2, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andFirstWorkDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("first_work_date not between", value1, value2, "firstWorkDate");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 25 11:05:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon Mar 25 11:05:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}